### ISSUE TITLE
Элемент cpa в элементе shop выдает ошибку

### ISSUE THREAD

**Issue by vsdm** [lireincore/ymlparser#2]
```xml
<?xml version="1.0" encoding="windows-1251"?>
<!DOCTYPE yml_catalog SYSTEM "shops.dtd">
<yml_catalog date="2016-12-02 08:11">
    <shop>
        <name>Shop.com.ua</name>
        <company>Интернет магазин Shop.com.ua</company>
        <url>www.shop.com.ua/</url>
        <cpa>0</cpa>
        <currencies>
            <currency id="UAH" rate="1"/>
        </currencies>
        <categories>
            <category id="1"><![CDATA[Test category]]></category>
        </categories>
        <offers>
            <offer id="1294928" type="vendor.model" available="true">
                <name><![CDATA[Test name]]></name>
                <url>http://www.shop.com.ua/1294928.html</url>
                <price>5430</price>
                <currencyId>UAH</currencyId>
                <categoryId>1</categoryId>
                <picture>http://www.shop.com.ua/1294928.png</picture>
                <delivery>true</delivery>
                <vendor><![CDATA[Test vendor]]></vendor>
                <model><![CDATA[Test model]]></model>
                <description><![CDATA[Test description]]></description>
            </offer>
        </offers>
    </shop>
</yml_catalog>
```

Этот xml выдает ошибку:
XMLReader::read():  Element 'cpa': This element is not expected. Expected is one of ( platform, version, agency, email, currencies )

В документации можно указывать cpa как и в элементе offers так и в элементе shop.

**Comment by lireincore** [comment]
Не проходит валидацию по xsd-схеме. Элемент `<cpa>,` по идее, должен идти последним, т.е. после `<categories>`. Но, судя по всему, сам яндекс не особо следит за этим. Проблему можно решить двумя способами:
1) `$yml->parse($filepath, null);` - передать вторым параметром `null`, тогда валидация по xsd-схеме делаться не будет (при этом валидаторы `$shop->isValid()` и `$offer->isValid()` - будут работать)
2) Передать вторым параметром путь к файлу с другой xsd-схемой `$yml->parse($filepath, 'path/to/schema.xsd');` (можно попробовать скачать xsd-схему, которую совсем недавно выложил сам яндекс [https://download.cdn.yandex.net/support/ru/webmaster/files/shops_with_byn.xsd](url)).

**Comment by vsdm** [comment]
Указание xsd от Яндекса решило проблемy
